import turtle
get_screen = turtle.Screen()
ricky = turtle.Turtle()
ricky.forward(150)
ricky.circle(30)
ricky.left(90)
ricky.clearstamp(34)
ricky.forward(200)
ricky.left(90)
ricky.forward(100)
ricky.circle(100)
ricky.forward(300)
ricky.color("black","blue")
ricky.begin_fill()
ricky.circle(60)
ricky.end_fill()
ricky.color("purple","pink")
ricky.begin_fill()
ricky.circle(100)
ricky.end_fill()
ricky.begin_poly()
ricky.forward(100)
ricky.right(60)
ricky.forward(150)
