import pyttsx3
pyttsx3.speak("Hello, I'm you interpreter!")
engine = pyttsx3.init()
rate = engine.getProperty('rate')
engine.setProperty('rate', 190)
engine.say("Hello World!")
engine.runAndWait()
engine.stop()
converter = pyttsx3.init()
rate1 = converter.getProperty('rate')
converter.setProperty('rate1', 170)
converter.setProperty('voice', 'english_rp+f3')
converter.say("Good Evening Boss.. Let's roll! Boss would you like to go through the recent updates?")
converter.runAndWait()
